/// Simple two-language string table. English is the default; Tamil is an option
/// in Settings. Stamp text on the photo always stays English so the burned-in
/// bitmap font renders correctly.
class S {
  S(this.lang);
  final String lang;

  static const Map<String, Map<String, String>> _t = {
    'en': {
      'app': 'Arul GPS Camera',
      'camera': 'Camera',
      'photos': 'Photos',
      'settings': 'Settings',
      'capture': 'Capture',
      'searching': 'Finding location',
      'gps_off': 'Location is off',
      'gps_denied': 'Location permission needed',
      'cam_denied': 'Camera permission needed',
      'open_settings': 'Open settings',
      'grant': 'Grant permission',
      'retry': 'Try again',
      'accuracy': 'Accuracy',
      'altitude': 'Altitude',
      'bearing': 'Bearing',
      'saved': 'Saved to gallery',
      'save_failed': 'Could not save the photo',
      'stamping': 'Stamping photo',
      'no_photos': 'No photos yet. Take one to get started.',
      'share': 'Share',
      'delete': 'Delete',
      'delete_q': 'Delete this photo?',
      'delete_note': 'It is removed from the app. The gallery copy stays.',
      'cancel': 'Cancel',
      'language': 'Language',
      'english': 'English',
      'tamil': 'Tamil',
      'stamp': 'Stamp',
      'show_map': 'Map thumbnail',
      'show_map_sub': 'Small map of the spot, left of the stamp',
      'show_compass': 'Compass and bearing',
      'show_address': 'Street address',
      'show_address_sub': 'Needs internet. Coordinates work offline.',
      'time_format': '24-hour time',
      'photo_quality': 'Photo width',
      'photo_quality_sub': 'Smaller width shares faster on WhatsApp',
      'grid': 'Grid lines',
      'about': 'About',
      'version': 'Version',
      'no_address': 'Address unavailable offline',
      'waiting_gps': 'Waiting for GPS fix',
      'weak_gps': 'Weak signal - move to open sky',
      'grant_cam_loc': 'Arul GPS Camera needs the camera and your location to stamp photos.',
      'perm_title': 'Two permissions to get started',
      'perm_intro': 'Both are used only while you are taking a photo. Nothing is uploaded anywhere.',
      'perm_cam': 'Camera',
      'perm_cam_why': 'To take the photo itself.',
      'perm_loc': 'Location',
      'perm_loc_why': 'To stamp the coordinates, address and bearing onto the photo.',
      'perm_allow': 'Allow both',
      'perm_blocked': 'Permission was blocked earlier. Open settings, turn on Camera and Location, then come back.',
      'perm_note': 'Without these the app cannot take a stamped photo.',
      'show_qr': 'Google Maps QR',
      'show_qr_sub': 'Scanning it opens the exact spot in Google Maps',
    },
    'ta': {
      'app': 'அருள் GPS கேமரா',
      'camera': 'கேமரா',
      'photos': 'படங்கள்',
      'settings': 'அமைப்புகள்',
      'capture': 'படம் எடு',
      'searching': 'இடம் தேடுகிறது',
      'gps_off': 'இருப்பிடம் அணைக்கப்பட்டுள்ளது',
      'gps_denied': 'இருப்பிட அனுமதி தேவை',
      'cam_denied': 'கேமரா அனுமதி தேவை',
      'open_settings': 'அமைப்புகளைத் திற',
      'grant': 'அனுமதி தருக',
      'retry': 'மீண்டும் முயல்க',
      'accuracy': 'துல்லியம்',
      'altitude': 'உயரம்',
      'bearing': 'திசை',
      'saved': 'கேலரியில் சேமிக்கப்பட்டது',
      'save_failed': 'படத்தை சேமிக்க முடியவில்லை',
      'stamping': 'படத்தில் விவரம் பதிகிறது',
      'no_photos': 'படங்கள் இல்லை. ஒன்று எடுத்து தொடங்குங்கள்.',
      'share': 'பகிர்',
      'delete': 'நீக்கு',
      'delete_q': 'இந்த படத்தை நீக்கவா?',
      'delete_note': 'செயலியிலிருந்து மட்டும் நீங்கும். கேலரி நகல் இருக்கும்.',
      'cancel': 'ரத்து',
      'language': 'மொழி',
      'english': 'ஆங்கிலம்',
      'tamil': 'தமிழ்',
      'stamp': 'முத்திரை',
      'show_map': 'வரைபடச் சிறுபடம்',
      'show_map_sub': 'முத்திரையின் இடதுபுறம் சிறு வரைபடம்',
      'show_compass': 'திசைகாட்டி',
      'show_address': 'முகவரி',
      'show_address_sub': 'இணையம் தேவை. அட்சரேகை ஆஃப்லைனிலும் வேலை செய்யும்.',
      'time_format': '24 மணி நேரம்',
      'photo_quality': 'பட அகலம்',
      'photo_quality_sub': 'சிறிய அகலம் WhatsApp-ல் விரைவாக பகிரும்',
      'grid': 'கட்டக் கோடுகள்',
      'about': 'பற்றி',
      'version': 'பதிப்பு',
      'no_address': 'முகவரி கிடைக்கவில்லை',
      'waiting_gps': 'GPS சமிக்ஞைக்கு காத்திருக்கிறது',
      'weak_gps': 'சமிக்ஞை குறைவு - திறந்தவெளிக்கு செல்லுங்கள்',
      'grant_cam_loc': 'படத்தில் இடத்தை பதிக்க கேமரா மற்றும் இருப்பிட அனுமதி தேவை.',
      'perm_title': 'தொடங்க இரண்டு அனுமதிகள்',
      'perm_intro': 'படம் எடுக்கும்போது மட்டுமே பயன்படும். எதுவும் வெளியே அனுப்பப்படாது.',
      'perm_cam': 'கேமரா',
      'perm_cam_why': 'படம் எடுப்பதற்கு.',
      'perm_loc': 'இருப்பிடம்',
      'perm_loc_why': 'அட்சரேகை, முகவரி, திசையை படத்தில் பதிக்க.',
      'perm_allow': 'இரண்டையும் அனுமதி',
      'perm_blocked': 'அனுமதி முன்பு தடுக்கப்பட்டது. அமைப்புகளில் கேமரா, இருப்பிடம் இரண்டையும் இயக்கி திரும்பி வாருங்கள்.',
      'perm_note': 'இவை இல்லாமல் முத்திரையிட்ட படம் எடுக்க முடியாது.',
      'show_qr': 'Google Maps QR',
      'show_qr_sub': 'ஸ்கேன் செய்தால் அந்த இடம் Google Maps-ல் திறக்கும்',
    },
  };

  String t(String key) => _t[lang]?[key] ?? _t['en']![key] ?? key;
}
